name: CI for Template

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    name: ${{ matrix.copier_config.name }} - Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.8', '3.9', '3.10']
        copier_config:
          - name: Base example
            package_name: example_project # The default package_name
            extra_flags: ''
            foldername: base_example

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Python dependencies
      run: |
        sudo apt-get update
        python -m pip install --upgrade pip
        python -m pip install copier
    
    - name: Generate package
      run: |
        copier copy --vcs-ref HEAD --defaults ${{ matrix.copier_config.extra_flags }} ./ ../test/${{ matrix.copier_config.foldername }}
        cd ../test/${{ matrix.copier_config.foldername }}
        cat .copier-answers.yml
    
    - name: Build package
      run: |
        cd ../test/${{ matrix.copier_config.foldername }}
        git init --initial-branch=main
        pip install .
        pip install .[dev]
    
    - name: pylint checks
      if: ${{ contains (matrix.copier_config.name, 'Base') }}
      run: |
        cd ../test/${{ matrix.copier_config.foldername }}
        python -m pylint --recursive=y ./src/ --rcfile=./src/.pylintrc
   
