name: CI for Template

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    name: ${{ matrix.copier_config.name }} - Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.8', '3.9', '3.10']
        copier_config:
          - name: Base example
            package_name: example_package # The default package_name
            extra_flags: ''
            foldername: base_example
          - name: Base example w/ module # Use some example module to confirm pytest/pylint
            package_name: example_package
            extra_flags: --data create_example_module=yes
            foldername: base_example_module

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Python dependencies
      run: |
        sudo apt-get update
        python -m pip install --upgrade pip
        python -m pip install copier
    
    - name: Generate package
      run: |
        copier copy --vcs-ref HEAD --defaults ${{ matrix.copier_config.extra_flags }} ./ ../test/${{ matrix.copier_config.foldername }}
        cd ../test/${{ matrix.copier_config.foldername }}
        cat .copier-answers.yml
    
    - name: Build package
      run: |
        cd ../test/${{ matrix.copier_config.foldername }}
        # initialize git
        git config --global user.email "tstname@example.com"
        git config --global user.name "Test Name"       
        git init --initial-branch=main
        # commit src which seems required so that site-utils contains rail/example_package
        # and import rail.example_package will function
        git add src
        git commit -m initial
        pip install .
        pip install .[dev]
    
    - name: pylint checks
      run: |
        cd ../test/${{ matrix.copier_config.foldername }}
        python -m pylint --recursive=y ./src/rail
   
    - name: Tests
      if: ${{ contains(matrix.copier_config.extra_flags, 'create_example_module=yes') }}
      run: |
        cd ../test/${{ matrix.copier_config.foldername }}
        python -m pytest tests --cov=rail/${{ matrix.copier_config.package_name }} --cov-report=xml
